# Helix theme: Brutal Solarized Light
# https://docs.helix-editor.com/themes.html#scopes
# https://github.com/helix-editor/helix/blob/master/runtime/themes/solarized_light.toml
# https://ethanschoonover.com/solarized/
# https://tonsky.me/blog/syntax-highlighting/

# Actual code
"comment" = { fg = "violet", modifiers = ["bold"] }
"constant" = { fg = "green" }
"string" = { fg = "cyan" }
"punctuation" = { fg = "base01" }
"keyword" = { fg = "blue" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "yellow" }
"diff.minus" = { fg = "red" }

# Markup
"markup.heading" = { fg = "blue", modifiers = ["bold"] }

# Normal ui font style
"ui.text" = { fg = "base1" }

# background
"ui.background" = { bg = "base03" }

"ui.virtual.whitespace" = { fg = "base01" }
"ui.virtual.inlay-hint" = { fg = "base01", modifiers = ["italic"] }
"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }

# line number column
"ui.linenr" = { fg = "base0", bg = "base02" }
# current line number column
"ui.linenr.selected" = { fg = "blue", modifiers = ["bold"] }
# cursorline
"ui.cursorline" = { bg = "base0" }

# status bar
"ui.statusline" = { fg = "base03", bg = "base0" }
"ui.statusline.normal" = { bg = "blue" }
"ui.statusline.insert" = { bg = "green" }
"ui.statusline.select" = { bg = "yellow" }

# inactive status bar
"ui.statusline.inactive" = { fg = "base1", bg = "base01" }

# Completion window, preview window
"ui.popup" = { bg = "base02" }
# Affect completion selection, cmd pop-up information selection
"ui.menu.selected" = { fg = "base02", bg = "base2"}
"ui.menu" = { fg = "base0", bg = "base02" }
# ??
"ui.window" = { fg = "base3" }
# Command line completion help information
"ui.help" = { modifiers = ["reversed"] }

# Shortcut window
"ui.popup.info" = { bg = "base1" }
# Shortcut font
"ui.text.info" = {fg = "base02", modifiers = ["bold"]}

# Affects picker list selection, shortcut key help window text
"ui.text.focus" = { fg = "blue", modifiers = ["bold"]}

# main cursor/selection
"ui.cursor.primary" = { fg = "base03", bg = "base1" }
"ui.cursor.select" = { fg = "base02", bg = "cyan" }

"ui.cursorline.primary" = { bg = "base02" }
"ui.cursorline.secondary" = { bg = "base025" }

"ui.selection" = { bg = "base0175" }
"ui.selection.primary" = { bg = "base015" }

"ui.virtual.indent-guide" = { fg = "base02" }
"ui.virtual.ruler" = { bg = "base02" }

# normal mode cursor
"ui.cursor" = {fg = "base02", bg = "cyan"}
"ui.cursor.insert" = {fg = "base03", bg = "base3"}
# The punctuation character matched by the current cursor
"ui.cursor.match" = { fg = "base02", bg = "base015" }

"warning" =  { fg = "orange", modifiers= ["bold", "underlined"] }
"error" = { fg = "red", modifiers= ["bold", "underlined"] }
"info" = { fg = "blue", modifiers= ["bold", "underlined"] }
"hint" = { fg = "base01", modifiers= ["bold", "underlined"] }

"diagnostic.warning" = { underline = { style = "curl", color = "orange" } }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.info" = { underline = { style = "curl", color = "blue" } }
"diagnostic.hint" = { underline = { style = "curl", color = "base01" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }


[palette]
red      = "#dc322f"
green    = "#859900"
yellow   = "#b58900"
blue     = "#268bd2"
magenta  = "#d33682"
cyan     = "#2aa198"
orange   = "#cb4b16"
violet   = "#6c71c4"

# dark getting darker
base0    = "#657b83"
base1    = "#586e75"
base2    = "#073642"
base3    = "#002b36"

# Lighter and lighter
base00   = "#839496"
base01   = "#93a1a1"
base015  = "#c5c8bd"
base0175 = "#dddbcc"
base02   = "#eee8d5"
base025  = "#f5eedb"
base03   = "#fdf6e3"
